### ISSUE TITLE
Include a GET method to retrieve the brand-new Prediction

### ISSUE THREAD

**Issue by luabida** [eduardocorrearaujo/tutorial_mosqlimate#1]
In the [Post model](https://github.com/eduardocorrearaujo/tutorial_mosqlimate/blob/main/Post%20model%20in%20the%20database.ipynb) notebook, it would be good to also have a GET method to show how to retrieve the prediction after it has been created, besides the predictions list screenshot

It would be something like:
```py
id = 9  # from res
url = f"https://api.mosqlimate.org/api/registry/predictions/{id}"
res = requests.get(url)
res.json()
```

**Comment by eduardocorrearaujo** [comment]
Solved.
